"use client";
import Link from "next/link";
import {ArrowLeft,CircleDollarSign,Clock3,LayoutDashboard,PackageCheck,ReceiptText,ShoppingBag,TrendingUp} from "lucide-react";
const orders=[["#SH1051","Marina Alves","R$ 86,90","Aguardando PIX","pending"],["#SH1050","Paulo Souza","R$ 59,90","Pago","paid"],["#SH1049","Camila Lima","R$ 72,80","Preparando","preparing"],["#SH1048","Rafael Costa","R$ 129,90","Saiu para entrega","delivery"],["#SH1047","Ana Luiza","R$ 44,90","Concluído","done"]];
const columns=["Novo","Pago","Preparando","Pronto","Entrega","Concluído"];
export default function Admin(){return <div className="min-h-screen bg-[#0b1116] text-[#f8f1e6]"><header className="border-b border-white/8 bg-[#11191f]"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-full bg-[#f15a46] font-serif font-bold">鮨</div><div><b>Sushi House</b><p className="text-xs text-[#849198]">Central de gestão</p></div></div><Link href="/" className="flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-sm"><ArrowLeft className="size-4"/>Ver loja</Link></div></header><main className="mx-auto max-w-7xl px-4 py-6 sm:px-6"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#e5bc70]">Visão geral</p><h1 className="mt-1 font-serif text-3xl font-bold">Olá, equipe Sushi House</h1><p className="mt-1 text-sm text-[#8e9ba1]">Acompanhe a operação de hoje.</p></div>
<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Pedidos hoje","17",ShoppingBag],["Faturamento","R$ 1.287,40",CircleDollarSign],["Ticket médio","R$ 75,72",TrendingUp],["Aguardando PIX","3",Clock3]].map(([label,value,Icon]:any)=><div key={label} className="rounded-2xl border border-white/8 bg-[#121a20] p-5"><Icon className="mb-4 size-5 text-[#e5bc70]"/><p className="text-xs uppercase tracking-wider text-[#7f8c92]">{label}</p><p className="mt-1 text-2xl font-extrabold">{value}</p></div>)}</div>
<section className="mt-7"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#e5bc70]">Tempo real</p><h2 className="mt-1 font-serif text-2xl font-bold">Pedidos recentes</h2></div><button className="rounded-lg bg-[#f15a46] px-4 py-2 text-sm font-bold">Novo pedido</button></div><div className="overflow-hidden rounded-2xl border border-white/8 bg-[#121a20]"><div className="hidden grid-cols-[1fr_1.4fr_1fr_1.2fr] border-b border-white/8 px-5 py-3 text-xs uppercase tracking-wider text-[#7f8c92] sm:grid"><span>Pedido</span><span>Cliente</span><span>Total</span><span>Status</span></div>{orders.map(o=><div key={o[0]} className="grid gap-2 border-b border-white/6 px-5 py-4 last:border-0 sm:grid-cols-[1fr_1.4fr_1fr_1.2fr] sm:items-center"><b>{o[0]}</b><span className="text-sm text-[#b6c0c4]">{o[1]}</span><span className="text-sm font-bold">{o[2]}</span><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-bold ${o[4]==="pending"?"bg-amber-400/12 text-amber-300":o[4]==="paid"?"bg-emerald-400/12 text-emerald-300":o[4]==="delivery"?"bg-sky-400/12 text-sky-300":"bg-white/7 text-[#c7d0d4]"}`}>{o[3]}</span></div>)}</div></section>
<section className="mt-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#e5bc70]">Fluxo da cozinha</p><h2 className="mb-4 mt-1 font-serif text-2xl font-bold">Kanban de pedidos</h2><div className="scrollbar-none flex gap-3 overflow-x-auto pb-3">{columns.map((c,i)=><div key={c} className="min-h-44 w-56 shrink-0 rounded-2xl border border-white/8 bg-[#121a20] p-4"><div className="flex items-center justify-between"><b className="text-sm">{c}</b><span className="grid size-6 place-items-center rounded-full bg-white/7 text-xs">{i<4?1:0}</span></div>{i<4&&<div className="mt-4 rounded-xl border border-white/8 bg-[#182128] p-3"><b className="text-sm">{orders[i][0]}</b><p className="mt-1 text-xs text-[#89969c]">{orders[i][1]}</p><p className="mt-3 text-xs font-bold text-[#e5bc70]">{orders[i][2]}</p></div>}</div>)}</div></section>
<section className="mt-7 grid gap-3 md:grid-cols-3">{[[PackageCheck,"Produtos","38 itens · 36 ativos"],[ReceiptText,"Categorias","15 categorias organizadas"],[LayoutDashboard,"Configurações","Entrega, horários e PIX"]].map(([Icon,title,desc]:any)=><button key={title} className="flex items-center gap-4 rounded-2xl border border-white/8 bg-[#121a20] p-5 text-left hover:border-[#f15a46]/35"><span className="grid size-11 place-items-center rounded-xl bg-[#f15a46]/10 text-[#f47765]"><Icon className="size-5"/></span><span><b>{title}</b><small className="mt-1 block text-[#849198]">{desc}</small></span></button>)}</section><p className="py-10 text-center text-xs text-[#657178]">Protótipo local · autenticação e persistência serão conectadas antes da publicação.</p></main></div>}
