export type Product={id:number;category:string;name:string;description:string;price:number;oldPrice?:number;badge?:string;pieces?:string;image:string};
const p=(id:number,category:string,name:string,description:string,price:number,oldPrice?:number,badge?:string,pieces?:string,_image?:string):Product=>({id,category,name,description,price,oldPrice,badge,pieces,image:`/products/optimized/${String(id).padStart(2,"0")}.webp`});
export const categories=["Ofertas","Combos","Combinados","Barcas","Entradas","Temakis","Uramakis","Hossomakis","Niguiris","Sashimis","Hot Rolls","Pratos Quentes","Porções","Molhos","Bebidas","Sobremesas"];
export const products:Product[]=[
p(1,"Ofertas","Combo Casal Sushi House","24 peças, 2 hot rolls especiais, 2 tarês e Coca-Cola 1L.",59.9,79.9,"MAIS PEDIDO","24 + 2","/products/combos/combo-casal-coca-cola.png"),
p(2,"Ofertas","Festival 40 Peças","Seleção do chef com salmão, kani, skin, 2 molhos e Coca-Cola 1,5L.",89.9,119.9,"INAUGURAÇÃO","40","/products/combos/festival-40-coca-cola.png"),
p(3,"Ofertas","Combo Individual Festival","12 peças, 5 hot rolls, molho tarê e Coca-Cola lata.",34.9,54.9,"ECONOMIZE R$ 20","17","/products/combos/combo-individual-coca-cola.png"),
p(4,"Ofertas","Combo Família 60 Peças","60 peças selecionadas, 10 hots, 4 molhos e Coca-Cola 2L.",129.9,159.9,"-19%","60 + 10","/products/combos/combo-familia-coca-cola.png"),
p(5,"Combos","Hot Lovers","20 hot rolls, cream cheese extra e molho tarê.",39.9,49.9,"OFERTA","20"),p(6,"Combos","Combo Salmon","Uramakis, niguiris, sashimis e hots de salmão.",74.9,undefined,undefined,"32"),p(7,"Combos","Combo House Premium","Seleção premium da casa para compartilhar.",109.9,undefined,undefined,"44"),
p(8,"Combinados","Combinado 15 Peças","Uramakis, hossomakis, niguiris e hot rolls.",36.9,undefined,undefined,"15"),p(9,"Combinados","Combinado 20 Peças","Seleção variada com salmão fresco.",44.9,59.9,"-25%","20"),p(10,"Combinados","Combinado 30 Peças","Clássicos da casa para duas pessoas.",62.9,84.9,"INAUGURAÇÃO","30"),p(11,"Combinados","Combinado 50 Peças","Uma seleção completa para a família.",99.9,139.9,"ECONOMIZE R$ 40","50"),
p(45,"Barcas","Barca Suizei","20 peças: 5 sashimis, 2 niguiris, 2 djows, 6 sushis e 5 hot rolls.",79.9,undefined,"BARCA JAPONESA","20","/products/boats/barca-suizei-20.png"),
p(46,"Barcas","Barca Jimmu","40 peças: 10 sashimis, 3 niguiris, 3 djows, 2 gunkans, 12 sushis e 10 hot rolls.",165.9,undefined,"PARA COMPARTILHAR","40","/products/boats/barca-jimmu-40.png"),
p(47,"Barcas","Barca Itoko","60 peças: 15 sashimis, 4 niguiris, 5 djows, 4 gunkans, 20 sushis e 12 hot rolls.",289.9,undefined,"PREMIUM","60","/products/boats/barca-itoko-60.png"),
p(48,"Barcas","Barca Umami Premium","100 peças: 30 sashimis, 8 niguiris, 10 djows, 8 gunkans, 24 sushis e 20 hot rolls. Somente sob encomenda.",519.9,undefined,"SOB ENCOMENDA","100","/products/boats/barca-umami-100.png"),
p(49,"Barcas","Barca Supremo","204 peças para grandes eventos: 50 sashimis, 20 niguiris, 20 djows, 14 gunkans, 60 sushis e 40 hot rolls. Somente sob encomenda.",798.9,undefined,"EVENTOS · SOB ENCOMENDA","204","/products/boats/barca-supremo-204.png"),
p(12,"Entradas","Sunomono","Pepino agridoce, gergelim e toque de limão.",12.9),p(13,"Entradas","Guioza Suíno","Pastéis orientais dourados e molho da casa.",22.9,undefined,undefined,"6"),p(14,"Entradas","Shimeji na Manteiga","Cogumelos salteados com shoyu e cebolinha.",24.9),
p(15,"Temakis","Temaki Salmão","Salmão em cubos, cebolinha e arroz japonês.",21.9,29.9,"OFERTA"),p(16,"Temakis","Temaki Philadelphia","Salmão, cream cheese e cebolinha na nori crocante.",23.9,32.9,"-27%"),p(17,"Temakis","Temaki Hot","Salmão empanado, cream cheese e tarê.",24.9),
p(18,"Uramakis","Uramaki Philadelphia","Salmão, cream cheese e gergelim.",19.9,26.9,"INAUGURAÇÃO","8"),p(19,"Uramakis","Uramaki Skin","Pele de salmão grelhada, pepino e tarê.",18.9,undefined,undefined,"8"),p(20,"Uramakis","Uramaki Califórnia","Kani, manga, pepino e gergelim.",18.9,undefined,undefined,"8"),
p(21,"Hossomakis","Hossomaki Salmão","Arroz japonês, salmão e alga nori.",17.9,undefined,undefined,"8"),p(22,"Hossomakis","Kappamaki","Pepino, arroz japonês e gergelim.",13.9,undefined,undefined,"8"),
p(23,"Niguiris","Niguiri Salmão","Fatia de salmão sobre arroz temperado.",19.9,undefined,undefined,"6"),p(24,"Niguiris","Niguiri Skin","Skin grelhado, tarê e cebolinha.",16.9,undefined,undefined,"6"),
p(25,"Sashimis","Sashimi Salmão","Cortes frescos e delicados de salmão.",29.9,39.9,"OFERTA","10"),p(26,"Sashimis","Sashimi Especial","Cortes especiais com crispy de alho-poró.",39.9,undefined,undefined,"10"),
p(27,"Hot Rolls","Hot Roll Philadelphia","Salmão, cream cheese, empanado e tarê.",19.9,27.9,"-29%","10"),p(28,"Hot Rolls","Hot Doritos","Hot crocante finalizado com nachos e tarê.",23.9,undefined,undefined,"10"),
p(29,"Pratos Quentes","Yakisoba Misto","Macarrão, carne, frango e legumes ao molho oriental.",35.9),p(30,"Pratos Quentes","Salmão Grelhado","Salmão, gohan, legumes e molho cítrico.",45.9),
p(31,"Porções","Camarão Crocante","Camarões empanados com molho especial.",34.9,undefined,undefined,"8"),p(32,"Porções","Hot Roll 5 Unidades","Porção pequena para completar o pedido.",9.9,undefined,undefined,"5"),
p(33,"Molhos","Molho Tarê","Agridoce tradicional da casa.",2),p(34,"Molhos","Molho Especial House","Cremoso e levemente picante.",3),
p(35,"Bebidas","Coca-Cola Original Lata","350 ml, gelada.",6,undefined,undefined,undefined,"/products/drinks/coca-cola-350ml.jpg"),
p(36,"Bebidas","Coca-Cola Original 1L","Garrafa PET gelada, perfeita para compartilhar.",8.9,undefined,undefined,undefined,"/products/drinks/coca-cola-1l.jpg"),
p(37,"Bebidas","Crystal Água com Gás","Água mineral com gás, garrafa de 500 ml gelada.",4.5,undefined,undefined,undefined,"/products/drinks/crystal-com-gas-500ml.jpg"),
p(39,"Bebidas","Schweppes Citrus","Refrigerante cítrico, lata de 350 ml gelada.",6.5,undefined,"REFRESCANTE",undefined,"/products/drinks/schweppes-citrus-350ml.png"),
p(40,"Bebidas","Oi Ocha Chá Verde","Chá verde japonês ITO EN, sem açúcar, garrafa de 500 ml.",12.9,undefined,"JAPONÊS",undefined,"/products/drinks/oi-ocha-green-tea.jpg"),
p(41,"Bebidas","Oi Ocha Hojicha","Chá verde japonês tostado ITO EN, sem açúcar, garrafa de 500 ml.",13.9,undefined,"JAPONÊS",undefined,"/products/drinks/oi-ocha-hojicha.jpg"),
p(38,"Sobremesas","Harumaki de Chocolate","Massa crocante com recheio cremoso.",16.9,undefined,undefined,"4"),
p(42,"Sobremesas","Harumaki de Banana com Chocolate","Quatro rolinhos crocantes com banana caramelizada e creme de chocolate com avelã.",24.9,undefined,"NOVO","4","/products/desserts/harumaki-banana-chocolate.png"),
p(43,"Sobremesas","Mochi Ice Cream Sortido","Seis mochis macios nos sabores matcha, morango e baunilha, com recheio cremoso gelado.",28.9,undefined,"JAPONÊS","6","/products/desserts/mochi-sortido.png"),
p(44,"Sobremesas","Cheesecake de Matcha","Fatia generosa de cheesecake cremoso com chá-verde matcha e base crocante.",33.9,undefined,"ESPECIAL",undefined,"/products/desserts/cheesecake-matcha.png")];
export const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
